config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  
  devise_for :users
  
  resources :chats do
    member do
      post "send_message"
    end
  end
  resources :bots do
    member do
      post "send_message"
      post "start"
      post "stop"
    end
  end

  namespace :api do
    resources :chats, only: [:show, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bot.rb
class Bot < ApplicationRecord
  encrypts :username, :token

  validates_presence_of :token, :username
end

app/models/chat.rb
class Chat
  include Mongoid::Document
  include Mongoid::Timestamps

  field :chat_id, type: Integer
  field :chat_type, type: String
  field :name, type: String

  embeds_many :messages

  validates_uniqueness_of :chat_id
  validates_presence_of :chat_id, :chat_type
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :text, type: String
  field :from, type: Integer
  field :first_name, type: String
  field :last_name, type: String
  field :bot, type: Boolean, default: false

  embedded_in :chat

  def name
    return "No name" unless first_name || last_name

    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :rememberable, :validatable
         #:registerable, :recoverable, 
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
end

app/controllers/api/chats_controller.rb
class Api::ChatsController < Api::ApplicationController
  before_action :set_chat, only: :show
  # GET /api/chats/1
  # GET /api/chats/1.json
  def show
  end

  # POST /api/chats
  # POST /api/chats.json
  def create
    @chat = Chats::Dispatcher.call(chat_params, message_params)

    if @chat.errors.empty?
      render :show, status: :created, location: @chat
    else
      render json: @chat.errors, status: :unprocessable_entity
    end
  end


  private
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def chat_params
      params.require(:chat).permit(:id, :type, :title, :first_name, :last_name)
    end

    def message_params
      params.require(:message).permit(:text, :from, :first_name, :last_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :set_bot, only: %i[ show edit update destroy send_message start stop]

  # GET /bots
  def index
    @bots = Bot.all
  end

  # GET /bots/1
  def show
    Bots::CheckStatus.call(@bot)
    render :show
  end

  # GET /bots/new
  def new
    @bot = Bot.new
  end

  # GET /bots/1/edit
  def edit
  end

  # POST /bots
  def create
    @bot = Bot.new(bot_params)

    if @bot.save
      redirect_to bot_url(@bot), notice: "Bot was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bots/1
  def update
    if @bot.update(bot_params)
      redirect_to bot_url(@bot), notice: "Bot was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /bots/
  def destroy
    Bots::Stop.call(@bot)
    @bot.destroy

    redirect_to bots_url, notice: "Bot was successfully destroyed.", status: :see_other
  end

  def send_message
    Messages::Sender.call(bot: @bot, message_params: message_params)
    redirect_to @bot, notice: "Mensaje enviado correctamente"
  # rescue ::Telegram::Bot::Exceptions::ResponseError => e
  #   redirect_to @bot, alert: e
  rescue StandardError => e
    redirect_to @bot, alert: "Ocurrio un error al intentar enviar el mensaje. #{e}"
  end

  def start
    Bots::Start.call(@bot)
    redirect_to @bot, notice: "El bot se inició correctamente"
  end

  def stop
    Bots::Stop.call(@bot)
    redirect_to @bot, notice: "El bot se apagó correctamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bot
      @bot = Bot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bot_params
      params.require(:bot).permit(:name, :username, :token)
    end

    def message_params
      params.permit(:text, :receiver)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy send_message]

  # GET /chat
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  def create
    @chat = Chat.new(chat_create_params)

    if @chat.save
      redirect_to chat_url(@chat), notice: "Chat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /chats/1
  def update
    if @chat.update(chat_update_params)
      redirect_to chat_url(@chat), notice: "Chat was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /chats/1
  def destroy
    @chat.destroy

    redirect_to chats_url, notice: "Chat was successfully destroyed.", status: :see_other
  end

  def send_message
    Messages::Sender.call(bot: bot, message_params: message_params)
    redirect_to @chat, notice: "Mensaje enviado correctamente"
  rescue StandardError => e
    redirect_to @chat, alert: "Ocurrio un error al intentar enviar el mensaje. #{e}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_update_params
      params.require(:chat).permit(:name)
    end

    def chat_create_params
      params.require(:chat).permit(:chat_id, :chat_type, :name)
    end

    def message_params
      params.permit(:text).merge({
        receiver: @chat.chat_id
      })
    end

    def bot_params
      params.permit(:bot_id)
    end

    def bot
      @bot ||= Bot.find(bot_params[:bot_id])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/api/chats_helper.rb
module Api::ChatsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/bots/_bot.html.slim
tr id="#{dom_id bot}"
  td
    = bot.id
  td
    = bot.name
  td
    = bot.username
  td 
    = bot.token
  td
    = link_to "Show this bot", bot

app/views/bots/_form.html.slim
.form-container.box
  = form_with(model: @bot) do |form|
    - if @bot.errors.any?
      div style="color: red"
        h2 = "#{pluralize(@bot.errors.count, "error")} prohibited this bot from being saved:"
        ul
          - @bot.errors.each do |error|
            li = error.full_message

    div
      = form.label :name, class: "label"
      .control
        = form.text_field :name, class:"input"
    div
      = form.label :username, class: "label"
      .control
        = form.text_field :username, class:"input"

    div
      = form.label :token, class: "label"
      .control
        = form.text_field :token, class:"input"

    div.mt-3.columns
      .column
        = form.submit class:"button is-success"
      .column.has-text-right
        = link_to("Show this bot", @bot, class:"button is-link mx-1") if @bot.persisted?
        = link_to "Back to bots", bots_path, class:"button is-warning mx-1"

app/views/bots/edit.html.slim
h1.title Editing bot

== render "form", bot: @bot

app/views/bots/index.html.slim
.columns
  .column
    h1.title Bots
  .column.has-text-right.mt-2
    = link_to "New bot", new_bot_path, class:"button is-primary"

#bots
  table.table.is-fullwidth
    thead
      tr
        th #
        th Nombre
        th Username
        th Token
        th
    - @bots.each do |bot|
      == render bot

app/views/bots/new.html.slim
h1.title New bot

== render "form", bot: @bot

app/views/bots/show.html.slim
.columns
  .column.is-6
    .card
      .card-content
        .media
          .media-left
            figure.image
              img src="https://bulma.io/images/placeholders/96x96.png"
          .media-content
            p.title.is-4
              = @bot.name
              = render(Bots::Status::Component.new(pid: @bot.pid))
            p.subtitle.is-6
              = "@#{@bot.username}"
      footer.card-footer
        => link_to "Edit this bot", edit_bot_path(@bot), class: "card-footer-item"
        - if @bot.pid.present?
          = link_to "Stop", stop_bot_path, class: "card-footer-item", data: { turbo_method: :post }
        - else
          = link_to "Start", start_bot_path, class: "card-footer-item", data: { turbo_method: :post }
        = link_to "Destroy this bot", @bot, data: {turbo_method: :delete, turbo_confirm: "Are you sure you want delete?" }, class: "card-footer-item is-danger"
  .column.is-6
    .card
      .card-header
        p.card-header-title Enviar mensaje
        div.card-header-icon
          span.icon
            i class="fa-regular fa-message"
      .card-content
        = form_with url: send_message_bot_path(@bot) do |f|
          .field
            = f.label :receiver, "Destinatario:", class:"label", required: true
            .select
              = f.select :receiver, Chat.all.map{ |chat| [chat.name, chat.chat_id] }, include_blank: true
          .field
            = f.text_area :text, placeholder:"Escribe tu mensaje", rows: 10, class: "textarea", required: true
          .actions.has-text-right
            = f.submit "Enviar", class: "button is-success" 
            
          
            

app/views/chats/_chat.html.slim
tr id="#{dom_id chat}"
  td
    = chat.chat_id
  td
    = chat.chat_type.capitalize
  td 
    = chat.name
  td
    = link_to "Show this chat", chat

app/views/chats/_form.html.slim
.form-container.box
  = form_with(model: @chat) do |form|
    - if @chat.errors.any?
      div style="color: red"
        h2 = "#{pluralize(@chat.errors.count, "error")} prohibited this chat from being saved:"
        ul
          - @chat.errors.each do |error|
            li = error.full_message
    div
      = form.label :name, class: "label"
      .control
        = form.text_field :name, class:"input"
    .columns
      .field.column
        = form.label :chat_id, "Chat ID", class: "label"
        .control
          = form.text_field :chat_id, class:"input", disabled: @chat.persisted?
      
      .field.column
        = form.label :chat_type, "Type:", class:"label", required: true
        .control
          .select.is-fullwidth
            = form.select :chat_type, [["Private", "private"], ["Group", "group"]], { include_blank: true }, { disabled: @chat.persisted? } 

    div.mt-3.columns
      .column
        = form.submit class:"button is-success"
      .column.has-text-right
        = link_to("Show this chat", @chat, class:"button is-link mx-1") if @chat.persisted?
        = link_to "Back to chats", chats_path, class:"button is-warning mx-1"

app/views/chats/edit.html.slim
h1.title Editing chat

== render "form", chat: @chat

app/views/chats/index.html.slim
.columns
  .column
    h1.title Chats
  .column.has-text-right.mt-2
    = link_to "New chat", new_chat_path, class:"button is-primary"

#chats
  table.table.is-fullwidth
    thead
      tr
        th Chat ID
        th Type
        th Title
        th
    - @chats.each do |chat|
      == render chat

app/views/chats/new.html.slim
h1.title New chat

== render "form", chat: @chat

app/views/chats/show.html.slim
.columns
  .column.is-5
    .card
      .card-content
        .media
          .media-left
            figure.image
              img src="https://bulma.io/images/placeholders/96x96.png"
          .media-content
            p.title.is-4
              = @chat.name
            p.is-6
              b Chat ID: 
              = "##{@chat.id}"
            p.is-6
              b Type: 
              = "#{@chat.chat_type}"
      footer.card-footer
        = link_to "Edit this chat", edit_chat_path(@chat), class: "card-footer-item"
        = link_to "Back to chats", chats_path, class: "card-footer-item"
        = link_to "Destroy this chat", @chat, data: {turbo_method: :delete, turbo_confirm: "Are you sure you want delete?" }, class: "card-footer-item is-danger"
  .column.is-7
    = render Chats::Conversations::Component.new(chat: @chat)

app/views/dashboard/index.html.slim
h1 Dashboard#index
p Find me in app/views/dashboard/index.html.slim

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Dashboard
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    div#app
      nav.hero.is-dark.is-small.has-shadow
        .hero-body 
          .container.has-text-centered
            .title 
              = link_to "My dashboard", root_path 
      section#main.main-content.columns.is-fullheight
        - if user_signed_in?
          aside.column.is-2.is-narrow-mobile.section
            = render("shared/nav_items")
        .container.column.is-10
          .section.px-1.pr-3
            = render("shared/alerts") if alert || notice
            = yield
      / footer.footer

app/views/shared/_alerts.slim
- if notice
  p class="notification is-success mt-2"
    = notice
- if alert
  p class="notification is-danger mt-2"
    = alert

app/views/shared/_nav_items.slim
p.menu-label Navigation
ul.menu-list
  li
    a href="#{root_path}"
      span.icon
        i.fa.fa-home
      | Home
    = link_to(bots_path)
      span.icon
        i class="fa-solid fa-robot"
      | Bots
    = link_to(chats_path)
      span.icon
        i class="fa-solid fa-message"
      | Chats
    = link_to(destroy_user_session_path, data: {turbo_method: :delete})
      span.icon
        i class="fa-solid fa-right-from-bracket"
      | Sign Out